### PR TITLE
implements ES parser using new list of bics. Fixes #14

### LINKED ISSUE #14: Spanish parser not working any more
The reason is, that in the list we use (http://www.bde.es/f/webbde/IFI/servicio/regis/ficheros/es/REGBANESP_CONESTAB_A.XLS), they removed the `BIC` column...

### PR DESCRIPTION
**Pull request by sluc23**
Updates Spanish bank list from our own published list in Github: https://github.com/ixiam/sepa_bic

### CODE REVIEW

**Comment by bjendres** [comment]
great, thanks @sluc23!

**Comment by francescbassas** [comment]
Thanks @sluc23 we will try to integrate it soon in our implementations.

**Comment by sluc23** [comment]
thanks @bjendres , any new release planned soon? would be good for us to have new ES parser tagged.. cheers!

**Comment by bjendres** [comment]
Yes, will do. Probably later today

**Comment by bjendres** [comment]
> thanks @bjendres , any new release planned soon? would be good for us to have new ES parser tagged.. cheers!

I have released ``1.5-beta2``. Let me know if everything works fine, and I'll to a ``1.5``

**Pull request merged**
