### PR TITLE
Update bic.xml

### PR DESCRIPTION
**Pull request by wintermoor**
translation strings added

### CODE REVIEW

**Comment by bjendres** [comment]
@wintermoor does this really work? Are you sure?

**Review by wintermoor — COMMENTED** [review]
No, not working. Excuse me.

**Comment by wintermoor** [comment]
Be carefull! Am a consultant, not a developer ;) 
You are right: PHP is not working in .xml 
Sorry for this mess.

**Comment by wintermoor** [comment]
But how to translate page title? Will be helpful for https://lab.civicrm.org/extensions/expenses , too.

**Comment by bjendres** [comment]
> Be carefull! Am a consultant, not a developer ;)
> You are right: PHP is not working in .xml
> Sorry for this mess.

No worries.

> But how to translate page title?

I usually just set the title in the page code again, like I did in the branch (#47) for improved l10n [HERE](https://github.com/Project60/org.project60.bic/commit/2db152eb318f7ed05f4b7d252c16b3fc4f45d358#diff-8927cbde83578988c3a52fe019d566573f4813b8974bfa396e5ea075b09c6957R10); there you can use the string translation function. If there's a way to do it in the routing XMLs, I'm not aware of it.

I'll go ahead and merge the l10n branch now, then you can have another go.

**Pull request closed without merging**
