### PR TITLE
Add supporting for French banks

### PR DESCRIPTION
**Pull request by scardinius**
Codes in local file which will be updated into full list in future #2

### CODE REVIEW

**Comment by systopia** [comment]
Hi @scardinius. I'm sorry, but I can't pull this. The problem is, that there is a legal issue providing and distributing this data. That's why none of our parsers contain any data, but pull it from external online sources - mostly the national banks directly. If you remove the CSV file and make your code download it from an online source, we can integrate it.

**Comment by scardinius** [comment]
Hi @systopia ok, I understand your point of view. The problem is that I don't know where relevant source is placed. On https://www.swiftrefdata.com/ is available free account only for 4 weeks.

**Comment by systopia** [comment]
Well, if you feel confident about the legal situation, you can host it yourself....

**Comment by systopia** [comment]
@scardinius: Any ideas on how to solve this? Do you think you can host this?

**Comment by systopia** [comment]
I would hate to discard a good PR :)

**Pull request closed without merging**
